### ISSUE TITLE
Unit scopes

### ISSUE THREAD

**Issue by Sorien** [casteng/i-pascal#45]
pls could you add support for unit scopes http://docwiki.embarcadero.com/RADStudio/Rio/en/Unit_Scope_Names

```pascal
uses
 Vcl.Forms; // undeclared identifier
```
in delphi you can specify default unit scopes like `Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell;System;Xml;Data;Datasnap;Web;Soap;Winapi;WinAPI.Foundation;System.Win;FMX`

in JB Idea project settings you have something named `Unit namespaces` but when I try 
`System;Vcl` or `System,Vcl` it seems to not be working  

```pascal
uses
 Forms; // undeclared identifier
```

Idea 2019.2
I-Pascal 2.40

**Comment by casteng** [comment]
The "Unit namespaces" setting in SDK settings is exactly the feature you are talking about. It's not included in autotests yet but I just tested manually and it seems to work.
What version of Delphi and for what architecture you are using?
What RTL directories did you set in Delphi SDK? One with sources or with .dcu?

**Comment by Sorien** [comment]
ok I didn't have all required directories included 

I have in unit namespaces `Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell;System;Xml;Data;Datasnap;Web;Soap;Winapi;System.Win`

![image](https://user-images.githubusercontent.com/1270275/64230599-8e363900-ceed-11e9-9116-81067a262959.png)

but still not all of them are working, it looks like the order is important 

e.g.

```pascal
uses
  Windows, Messages, Generics.Defaults, DB;
```
when I use `Winapi;Data;System;` `Generics.Defaults` can't be found 
when I change it to `Winapi;System;Data;` `Generics.Defaults` & `DB` can't be found

**Comment by casteng** [comment]
Fixed in v2.50

**Comment by Sorien** [comment]
it's better but still not ok 

```pascal
unit Test;

interface

uses
  Windows, Messages, Classes, SysUtils, Graphics, Controls, StdCtrls, Forms, U_ParentEdit, DBCtrls, DB, Mask, Buttons,
  JvComponentBase, JvComCtrls, JvExMask, JvDBControls, TB2Item, PrnDbgeh, DPControls, DPDBEdits, DPEdits,
  JvToolEdit, ExtCtrls;
```

![image](https://user-images.githubusercontent.com/1270275/68658612-1102f200-0536-11ea-9be4-91ca17d4097d.png)

unit Windows (WinApi.Windows) is in C:\Program Files (x86)\Embarcadero\Studio\20.0\source\rtl\win

![image](https://user-images.githubusercontent.com/1270275/68658866-8bcc0d00-0536-11ea-9394-9c0a84625c41.png)

unit namespaces
`Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell;System;Xml;Data;Datasnap;Web;Soap;Winapi;WinAPI.Foundation;System.Win;FMX`

**Comment by fireundubh** [comment]
> when I try System;Vcl or System,Vcl it seems to not be working

It was working for me in 2.10 but no longer in 2.50.
